### ISSUE TITLE
phantomjs 이후에 인터파크부분 아티스트가 이상함

### ISSUE THREAD

**Issue by saanghyuk** [saanghyuk/crawlingClass#17]
try:
            browser.find_element_by_xpath("//*[@id='TabA']/div[2]/ul[1]/li[4]/dl/dd/span[2]/a").click()
        except NoSuchElementException:
            browser.find_element_by_xpath("//*[@id='TabA']/div[2]/ul[1]/li[3]/dl/dd/span[2]/a").click()
            
        time.sleep(0.1)
        browser.switch_to_frame(browser.find_element_by_id("ifrTabC"))

인터파크 티켓은 phantomjs로 브라우져를 바꿨을 때, 아티스트가 아예 
[] 빈 객체가 옴.

**Comment by saanghyuk** [comment]
나머지 다 되는데 이 부분은 어떻게 해도 안됨

**Comment by saanghyuk** [comment]
어디가 잘못된건지 눈에 보이질 않아서 헤매던 중, 스크린샷 기능이 있음을 확인
스크린 샷을 찍어 보니 일단 '더보기' 버튼을 클릭까지 한것을 확인
그럼 iframe으로 전환되는게 안됬거나,
page_source를 가지고 오는게 안됬거나 둘중 하나!

**Comment by saanghyuk** [comment]
swith frame은 구글 10페이지까지 다 뒤져서 오만 방법으로 다해봄. 대기 시간도 주고, 명령어도 바꿔보고 다 해봤는데 안된다. 그러면 page_source를 못가지고 온건가?

**Comment by saanghyuk** [comment]
frame switch 하고 나서 page_source를 하는데 
그걸 프린트 한게 왜 <html><head></head><body marginwidth="0" marginheight="0"></body></html> 이렇게 밖에 안나올까.

**Comment by saanghyuk** [comment]
switching이 되었으면 browser.find_element_by_class_name('iframe 내부 클래스 이름') 이런게 먹어야 하는데 요소를 못찾겠다고 한다. 그럼 switching이 안된걸로 추론해 볼 수 있다.

**Comment by saanghyuk** [comment]
중간중간에 time.sleep(30) 씩 줄마다 넣어도 결과가 똑같은걸 보니, 시간의 문제는 아닌것 같다.

**Comment by saanghyuk** [comment]
python_crawler/Phantom/InterPark_Phantom.py 
@Kyeongrok 
선생님 이 부분에 중간에 주석 매우 많은부분 도저히 모르겠습니다.... 
iframe으로 switch 한 후에 page_source를 해도 소스가 오지 않습니다..
하루종일 찾아다녔는데 모르겠습니다.ㅠㅠ

**Comment by saanghyuk** [comment]
https://stackoverflow.com/questions/23581291/python-selenium-with-phantomjs-empty-page-source

**Comment by Kyeongrok** [comment]
iframe에 출력되는 페이지를 찾아보고 직접 호출 해보세요

**Comment by saanghyuk** [comment]
iframe만 호출해도 오지 않습니다. 똑같은 코드로 chrome driver, phantom js만 바꿨을 뿐인데 아이프레임으로 옮기는 순가 page_source를 호출해도 빈 소스만 옵니다!

**Comment by saanghyuk** [comment]
headless chrome으로 바꾸고 완료!
